name = "BioAlignments"
uuid = "00701ae9-d1dc-5365-b64a-a3a3ebf5695e"
authors = ["Kenta Sato <bicycle1885@gmail.com>", "Ben J. Ward <benjward@protonmail.com>"]
version = "1.0.1"

[deps]
BioGenerics = "47718e42-2ac5-11e9-14af-e5595289c2ea" # Note: required for distance function.
BioSequences = "7e6ae17a-c86d-528c-b3b9-7f778a29fe59"
BioSymbols = "3c28c6f8-a34d-59c4-9654-267d177fcfa9"
IntervalTrees = "524e6230-43b7-53ae-be76-1e9e4d08d11b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "0.7,1"
BioGenerics = "0.1"
BioSequences = "2"
BioSymbols = "4"
IntervalTrees = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
